command /trash:
	trigger:
		set {_gui} to a new chest inventory with 6 row with name "Trash Can" 
		set slot 0-52 of {_gui} to air
		set slot 53 of {_gui} to orange stained glass pane named "&6Close Bin to Remove Items"
		open {_gui} to player


on inventory click:
	if name of event-inventory is "Trash Can":
		if index of event-slot = 53:
			cancel event
			send "&6Close Bin to Remove Items" to player
			
			
#For Support Contact me on Discord at ωilliam#5384			
			
			
			